### ISSUE TITLE
Hashtag Filter

### ISSUE THREAD

**Issue by Technik-Tueftler** [Technik-Tueftler/TwitchHenCommander#53]
# What
Create a Blacklist for hashtags which are not allowed on stream

# Idea
Build a string with all blacklist hashtags and check new hashtags 
```
blacklist = "#dasnicht#unddasauchnicht#"
check = "#dasnich#"
if check in blacklist:
    print("Hashtag nicht erlaubt")
else:
    print("Hashtag ist erlaubt")
```

# ToDo
- [x] Add command to set hashtags to blacklist
- [x] Read at bot start a txt and add new blacklist hashtags
- [x] Write with bot ends new hashtags
